# Generated by Django 5.2.12 on 2026-04-03 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Тақырып')),
                ('body', models.TextField(verbose_name='Мәтін')),
                ('published_at', models.DateField(verbose_name='Күні')),
            ],
            options={
                'verbose_name': 'Жаңалық',
                'verbose_name_plural': 'Жаңалықтар',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Пән атауы')),
            ],
            options={
                'verbose_name': 'Пән',
                'verbose_name_plural': 'Пәндер',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(verbose_name='Сынып (сан)')),
                ('letter', models.CharField(max_length=4, verbose_name='Литер')),
                ('slug', models.SlugField(help_text='мысалы: 5a, 9b', unique=True, verbose_name='Слаг (URL)')),
            ],
            options={
                'verbose_name': 'Сынып',
                'verbose_name_plural': 'Сыныптар',
                'ordering': ['grade', 'letter'],
                'constraints': [models.UniqueConstraint(fields=('grade', 'letter'), name='portal_schoolclass_grade_letter_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=80, verbose_name='Тегі')),
                ('first_name', models.CharField(max_length=80, verbose_name='Аты')),
                ('middle_name', models.CharField(blank=True, max_length=80, verbose_name='Әкесінің аты')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('position', models.CharField(blank=True, max_length=120, verbose_name='Лауазымы')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='portal.subject', verbose_name='Пәндер')),
            ],
            options={
                'verbose_name': 'Мұғалім',
                'verbose_name_plural': 'Мұғалімдер',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Дүйсенбі'), (1, 'Сейсенбі'), (2, 'Сәрсенбі'), (3, 'Бейсенбі'), (4, 'Жұма'), (5, 'Сенбі'), (6, 'Жексенбі')], verbose_name='Апта күні')),
                ('lesson_number', models.PositiveSmallIntegerField(verbose_name='Сабақ №')),
                ('room', models.CharField(blank=True, max_length=32, verbose_name='Кабинет')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='portal.schoolclass', verbose_name='Сынып')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_slots', to='portal.subject', verbose_name='Пән')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_slots', to='portal.teacher', verbose_name='Мұғалім')),
            ],
            options={
                'verbose_name': 'Сабақ слоты',
                'verbose_name_plural': 'Сабақ кестесі',
                'ordering': ['school_class', 'weekday', 'lesson_number'],
                'constraints': [models.UniqueConstraint(fields=('school_class', 'weekday', 'lesson_number'), name='portal_scheduleslot_class_day_lesson_uniq')],
            },
        ),
    ]
