# Generated by Django 5.2.12 on 2026-04-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_seed_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='body_en',
            field=models.TextField(blank=True, verbose_name='Текст (англ.)'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='body_ru',
            field=models.TextField(blank=True, verbose_name='Мәтін (орыс)'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_en',
            field=models.CharField(blank=True, max_length=220, verbose_name='Заголовок (англ.)'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_ru',
            field=models.CharField(blank=True, max_length=220, verbose_name='Тақырып (орыс)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Атауы (ағыл.)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_ru',
            field=models.CharField(blank=True, max_length=120, verbose_name='Атауы (орыс)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Должность (англ.)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position_ru',
            field=models.CharField(blank=True, max_length=120, verbose_name='Лауазым (орыс)'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=models.TextField(verbose_name='Мәтін (қаз)'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(max_length=220, verbose_name='Тақырып (қаз)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Пән атауы (қаз)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, max_length=120, verbose_name='Лауазымы (қаз)'),
        ),
    ]
